site_name: Eric Julianto

theme:
  name: material
  palette:
    primary: black
    accent: red
  features:
    - navigation.tabs

nav:
  - Home: "index.html"
  - Learn:
    - Intro To Programming: "pages/learn/intro_to_programming.md"
    - Python:
      - Basic Python:
        - Intro to Python: "pages/learn/L1_basic_python/intro.md"
      - Data Science:
        - Intro to Data Science: "pages/learn/L2_data_science/intro.md"
  - Projects: "pages/projects/projects.md"