site_name: Eric Julianto

theme:
  name: material
  palette:
    primary: black
    accent: red
  features:
    - navigation.tabs

nav:
  - Home: "index.html"
  - Tutorial:
    - Basic Python: "pages/tutorial/basic_python.md"
  - About: "about.md"